services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: tms-app
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: tms-nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:16
    container_name: tms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tms
      POSTGRES_USER: tms
      POSTGRES_PASSWORD: tms123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: tms-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit
    container_name: tms-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data: