<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vz&#225;jemn&#233; n&#225;klady | TMS</title>
    <style>
        *{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#10213d;font-family:Arial,sans-serif}.page{max-width:1460px;margin:0 auto;padding:24px 28px 60px}.back{color:#173b72;font-weight:700;text-decoration:none}.head{display:flex;justify-content:space-between;gap:16px;align-items:center}h1{margin:26px 0 6px}.lead,.muted{color:#64748b}.panel{background:#fff;border:1px solid #d8e1ed;border-radius:14px;padding:18px;margin-top:18px}.filters{display:grid;grid-template-columns:2fr 1fr 1fr auto auto;gap:10px;align-items:end}.field{display:grid;gap:6px}label{font-size:13px;font-weight:700}input,select,button{font:inherit;border:1px solid #cbd5e1;border-radius:8px;padding:10px}button{background:#173b72;color:#fff;border:0;font-weight:700;cursor:pointer}.secondary{background:#e8eef7;color:#173b72}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;margin-top:14px;min-width:1050px}th,td{padding:11px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}th{background:#f8fafc;font-size:13px}.badge{display:inline-block;padding:5px 8px;border-radius:999px;background:#e2e8f0;font-size:12px;font-weight:700}.confirmed,.shared{background:#dcfce7;color:#166534}.disputed{background:#fef3c7;color:#92400e}.reversed{background:#fee2e2;color:#991b1b}.draft,.private{background:#e2e8f0;color:#334155}.footer{display:flex;justify-content:space-between;align-items:center;margin-top:14px}.pager{display:flex;gap:8px;align-items:center}.message{margin-top:12px;padding:10px;border-radius:8px;background:#eef2ff}.error{background:#fee2e2;color:#991b1b}.hidden{display:none!important}.modal{position:fixed;inset:0;background:#0008;display:grid;place-items:center;padding:20px;z-index:5}.dialog{width:min(920px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:14px;padding:20px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.card{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:12px}.card span{display:block;color:#64748b;font-size:12px}.card strong{display:block;margin-top:6px}.audit{margin-top:14px}.audit-item{padding:10px 0;border-bottom:1px solid #e2e8f0}@media(max-width:850px){.filters,.cards{grid-template-columns:1fr 1fr}}@media(max-width:560px){.page{padding:18px}.filters,.cards{grid-template-columns:1fr}}
    </style>
</head>
<body>
<main class="page">
    <div class="head"><a class="back" href="/settings">&larr; Nastaven&#237;</a><button id="refresh" class="secondary">Obnovit</button></div>
    <h1>Vz&#225;jemn&#233; n&#225;klady</h1>
    <p class="lead">Spr&#225;va zapo&#269;itateln&#253;ch n&#225;klad&#367; mezi hlavn&#237;m a extern&#237;m dopravcem v&#269;etn&#283; auditovan&#253;ch zm&#283;n stavu.</p>
    <section class="panel">
        <div class="filters">
            <div class="field"><label for="search">Hledat</label><input id="search" placeholder="Popis, zdroj nebo ve&#345;ejn&#233; ID"></div>
            <div class="field"><label for="status">Stav</label><select id="status"><option value="">V&#353;echny</option><option value="draft">Koncept</option><option value="confirmed">Potvrzeno</option><option value="disputed">Rozporov&#225;no</option><option value="reversed">Stornov&#225;no</option></select></div>
            <div class="field"><label for="direction">Sm&#283;r</label><select id="direction"><option value="">V&#353;echny</option><option value="receivable">Pohled&#225;vka</option><option value="payable">Z&#225;vazek</option></select></div>
            <button id="filter">Filtrovat</button><button id="reset" class="secondary">Zru&#353;it filtr</button>
        </div>
        <div id="message" class="message hidden"></div>
        <div class="table-wrap"><table><thead><tr><th>Popis</th><th>Protistrana</th><th>Obdob&#237;</th><th>Sm&#283;r</th><th>&#268;&#225;stka</th><th>Stav</th><th>Viditelnost</th><th>Akce</th></tr></thead><tbody id="rows"></tbody></table></div>
        <div class="footer"><span id="total">Celkem 0 z&#225;znam&#367;</span><div class="pager"><button id="previous" class="secondary">P&#345;edchoz&#237;</button><span id="pageInfo">Strana 1 z 1</span><button id="next" class="secondary">Dal&#353;&#237;</button></div></div>
    </section>
</main>
<div id="detailModal" class="modal hidden"><section class="dialog"><div class="head"><h2 id="detailTitle">Detail vz&#225;jemn&#233;ho n&#225;kladu</h2><button id="closeDetail" class="secondary">Zav&#345;&#237;t</button></div><div id="detailCards" class="cards"></div><div id="lifecycleActions" class="head" style="justify-content:flex-start;margin-top:14px"></div><h3>Zdrojov&#253; sn&#237;mek</h3><pre id="sourceSnapshot"></pre><h3>Auditn&#237; historie</h3><div id="audit" class="audit"></div></section></div>
<script>
const token=sessionStorage.getItem('tms_mvp_token')||'';
const organization=sessionStorage.getItem('tms_mvp_organization_id')||'1';
let page=1,lastPage=1,activeCharge=null;
const esc=value=>String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
const labels={draft:'Koncept',confirmed:'Potvrzeno',disputed:'Rozporovano',reversed:'Stornovano',private:'Soukrome',shared:'Sdileno',receivable:'Pohledavka',payable:'Zavazek'};
const money=(minor,currency)=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:currency||'CZK'}).format(Number(minor||0)/100);
const date=value=>value?new Intl.DateTimeFormat('cs-CZ').format(new Date(value)):'-';
function message(text,error=false){const node=document.querySelector('#message');node.textContent=text;node.className=text?`message${error?' error':''}`:'message hidden'}
async function api(path,options={}){const headers=new Headers(options.headers||{});headers.set('Accept','application/json');headers.set('X-Organization-ID',organization);if(token)headers.set('Authorization',`Bearer ${token}`);const response=await fetch(path,{...options,headers});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||`HTTP ${response.status}`);return payload.data||payload}
function query(){const params=new URLSearchParams({page:String(page),per_page:'25'});for(const [id,key] of [['search','search'],['status','status'],['direction','direction']]){const value=document.querySelector(`#${id}`).value.trim();if(value)params.set(key,value)}return params}
async function load(){try{message('');const data=await api(`/api/v1/financial-mutual-charges?${query()}`),items=data.items||[],pagination=data.pagination||{};lastPage=pagination.last_page||1;document.querySelector('#rows').innerHTML=items.map(item=>`<tr><td><b>${esc(item.description)}</b><br><span class="muted">${esc(item.category)} | revize ${esc(item.revision)}</span></td><td>${esc(item.counterparty_type)} #${esc(item.counterparty_organization_id||item.counterparty_driver_id||'-')}</td><td>${esc(date(item.service_period_from))} - ${esc(date(item.service_period_until))}</td><td><span class="badge ${esc(item.direction)}">${esc(labels[item.direction]||item.direction)}</span></td><td><b>${esc(money(item.amount_minor,item.currency))}</b></td><td><span class="badge ${esc(item.status)}">${esc(labels[item.status]||item.status)}</span></td><td><span class="badge ${esc(item.visibility_status)}">${esc(labels[item.visibility_status]||item.visibility_status)}</span></td><td><button class="secondary" data-detail="${esc(item.public_id)}">Otevrit detail</button></td></tr>`).join('')||'<tr><td colspan="8">Zadne vzajemne naklady.</td></tr>';document.querySelector('#total').textContent=`Celkem ${pagination.total||0} zaznamu`;document.querySelector('#pageInfo').textContent=`Strana ${pagination.current_page||1} z ${lastPage}`;document.querySelector('#previous').disabled=page<=1;document.querySelector('#next').disabled=page>=lastPage;document.querySelectorAll('[data-detail]').forEach(button=>button.onclick=()=>openDetail(button.dataset.detail))}catch(error){message(error.message,true)}}
function renderLifecycleActions(item){const owner=Number(item.owner_organization_id)===Number(organization),actions=[];if(owner&&item.status==='draft')actions.push(['confirm','Potvrdit a sdilet','']);if(item.status==='confirmed')actions.push(['dispute','Rozporovat','secondary']);if(owner&&item.status!=='reversed')actions.push(['reverse','Stornovat','secondary']);document.querySelector('#lifecycleActions').innerHTML=actions.map(([action,label,style])=>`<button class="${style}" data-lifecycle-action="${action}">${label}</button>`).join('');document.querySelectorAll('[data-lifecycle-action]').forEach(button=>button.onclick=()=>transitionCharge(button.dataset.lifecycleAction))}
async function transitionCharge(action){if(!activeCharge)return;const reason=prompt('Uvedte duvod akce (alespon 3 znaky):','Rucni rozhodnuti ve financni administraci.');if(reason===null||reason.trim().length<3)return;try{await api(`/api/v1/financial-mutual-charges/${activeCharge.public_id}/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idempotency_key:crypto.randomUUID(),expected_revision:Number(activeCharge.revision),reason:reason.trim()})});message('Lifecycle akce byla auditne ulozena.');await openDetail(activeCharge.public_id);await load()}catch(error){message(error.message,true)}}
async function openDetail(id){try{const item=await api(`/api/v1/financial-mutual-charges/${id}`);activeCharge=item;document.querySelector('#detailTitle').textContent=item.description||'Detail vzajemneho nakladu';document.querySelector('#detailCards').innerHTML=`<div class="card"><span>Castka</span><strong>${esc(money(item.amount_minor,item.currency))}</strong></div><div class="card"><span>Smer</span><strong>${esc(labels[item.direction]||item.direction)}</strong></div><div class="card"><span>Stav</span><strong>${esc(labels[item.status]||item.status)}</strong></div><div class="card"><span>Viditelnost</span><strong>${esc(labels[item.visibility_status]||item.visibility_status)}</strong></div>`;renderLifecycleActions(item);document.querySelector('#sourceSnapshot').textContent=JSON.stringify(item.source_snapshot||{},null,2);document.querySelector('#audit').innerHTML=(item.events||[]).map(event=>`<div class="audit-item"><b>${esc(event.event_type)}</b> | revize ${esc(event.revision)}<br><span class="muted">${esc(event.reason||'')} | ${esc(date(event.occurred_at))}</span></div>`).join('')||'<p class="muted">Bez auditnich udalosti.</p>';document.querySelector('#detailModal').classList.remove('hidden')}catch(error){message(error.message,true)}}
document.querySelector('#filter').onclick=()=>{page=1;load()};document.querySelector('#reset').onclick=()=>{document.querySelector('#search').value='';document.querySelector('#status').value='';document.querySelector('#direction').value='';page=1;load()};document.querySelector('#refresh').onclick=load;document.querySelector('#previous').onclick=()=>{if(page>1){page--;load()}};document.querySelector('#next').onclick=()=>{if(page<lastPage){page++;load()}};document.querySelector('#closeDetail').onclick=()=>document.querySelector('#detailModal').classList.add('hidden');load();
</script>
</body>
</html>