<!doctype html>
<html lang="cs">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>P&#345;ehled tankov&#225;n&#237; | TMS</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#172033;font:14px Arial,sans-serif}.page{max-width:1500px;margin:auto;padding:28px}.top,.head,.actions,.pagination{display:flex;gap:10px;align-items:center;justify-content:space-between;flex-wrap:wrap}.back{color:#334155;font-weight:700;text-decoration:none}h1{margin:18px 0 4px}.lead{color:#64748b}.panel{background:#fff;border:1px solid #dbe3ee;border-radius:14px;padding:18px;margin-top:18px}.filters{display:grid;grid-template-columns:repeat(6,minmax(145px,1fr));gap:10px;align-items:end}.field{display:grid;gap:6px}label{font-weight:700}input,select,button{font:inherit;border:1px solid #cbd5e1;border-radius:8px;padding:10px;min-width:0}button,.button{background:#173b72;color:#fff;border:0;font-weight:700;cursor:pointer;text-decoration:none;display:inline-block}.secondary{background:#e8eef7;color:#173b72}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;margin-top:14px;min-width:1120px}th,td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}th{background:#f8fafc;white-space:nowrap}.muted{color:#64748b}.driver-change{color:#7c3aed;font-weight:700}.message{margin-top:12px;padding:10px;border-radius:8px;background:#eef2ff}.error{background:#fee2e2;color:#991b1b}.hidden{display:none!important}.modal{position:fixed;inset:0;background:#0008;display:grid;place-items:center;padding:20px}.dialog{background:#fff;border-radius:14px;padding:20px;width:min(720px,100%)}.dialog-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.history{margin-top:12px;padding:12px;background:#f8fafc;border-radius:8px;max-height:220px;overflow:auto}.history-item{padding:8px 0;border-bottom:1px solid #e2e8f0}@media(max-width:900px){.filters{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.filters,.dialog-grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<main class="page">
<div class="top"><a class="back" href="/settings">&larr; Nastaven&#237;</a><div class="actions"><a class="button secondary" href="/settings/fuel-imports">Importy soubor&#367;</a><button id="reload" class="secondary">Obnovit</button></div></div>
<h1>P&#345;ehled tankov&#225;n&#237;</h1>
<p class="lead">V&#353;echna importovan&#225; tankov&#225;n&#237; na jednom m&#237;st&#283;, v&#269;etn&#283; skute&#269;n&#233;ho &#345;idi&#269;e.</p>
<section class="panel">
<form id="filters" class="filters">
<div class="field"><label for="dateFrom">Od</label><input id="dateFrom" type="date"></div>
<div class="field"><label for="dateTo">Do</label><input id="dateTo" type="date"></div>
<div class="field"><label for="provider">Poskytovatel</label><select id="provider"><option value="">V&#353;ichni</option><option>ORLEN</option><option>MOL</option></select></div>
<div class="field"><label for="driver">Skute&#269;n&#253; &#345;idi&#269;</label><select id="driver"><option value="">V&#353;ichni &#345;idi&#269;i</option></select></div>
<div class="field"><label for="card">Karta</label><input id="card" type="search" placeholder="Posledn&#237; 4 &#269;&#237;slice"></div>
<div class="field"><label for="search">Hledat</label><input id="search" type="search" placeholder="Stanice, produkt, SPZ"></div>
<div class="actions"><button type="submit">Pou&#382;&#237;t filtry</button><button type="button" id="reset" class="secondary">Zru&#353;it filtry</button></div>
</form>
<div id="message"></div>
</section>
<section class="panel"><div class="head"><div><h2 style="margin:0">Tankov&#225;n&#237;</h2><span id="total" class="muted"></span></div><label>Na str&#225;nku <select id="perPage"><option>15</option><option selected>25</option><option>50</option><option>100</option></select></label></div>
<div class="table-wrap"><table><thead><tr><th>Datum a &#269;as</th><th>Stanice</th><th>Produkt</th><th>Mno&#382;stv&#237;</th><th>Celkem</th><th>Karta</th><th>Dr&#382;itel karty</th><th>Skute&#269;n&#253; &#345;idi&#269;</th><th>Vozidlo</th><th></th></tr></thead><tbody id="rows"></tbody></table></div>
<div class="pagination"><button id="previous" class="secondary">P&#345;edchoz&#237;</button><span id="pageInfo"></span><button id="next" class="secondary">Dal&#353;&#237;</button></div></section>
</main>
<div id="modal" class="modal hidden"><div class="dialog"><h2>Zm&#283;nit skute&#269;n&#233;ho &#345;idi&#269;e</h2><div id="summary"></div><div class="dialog-grid"><div class="field"><label for="actualDriver">Skute&#269;n&#253; &#345;idi&#269;</label><select id="actualDriver"></select></div><div class="field"><label for="reason">D&#367;vod zm&#283;ny</label><input id="reason" maxlength="500" placeholder="Nap&#345;. zapomenut&#225; karta"></div></div><div class="actions" style="margin-top:12px"><button id="saveDriver">Ulo&#382;it zm&#283;nu</button><button id="historyToggle" class="secondary">Zobrazit historii</button><button id="close" class="secondary">Zru&#353;it</button></div><div id="history" class="history hidden"></div></div></div>
<script>
const token=sessionStorage.getItem('tms_mvp_token')||'',org='1';let page=1,lastPage=1,filterDrivers=[],activeId=null,attribution=null;
const api=async(path,opt={})=>{const h=new Headers(opt.headers||{});h.set('Accept','application/json');h.set('X-Organization-ID',org);if(token)h.set('Authorization',`Bearer ${token}`);const r=await fetch(path,{...opt,headers:h});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(Object.values(b.errors||{}).flat().join(' ')||b.message||`HTTP ${r.status}`);return b.data};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(v,c)=>`${Number(v||0).toLocaleString('cs-CZ',{minimumFractionDigits:2,maximumFractionDigits:2})} ${c||''}`;
const number=v=>Number(v||0).toLocaleString('cs-CZ',{maximumFractionDigits:3});
const sourceDate=v=>{const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})[T ](\d{2}):(\d{2})(?::(\d{2}))?/);return m?`${Number(m[3])}. ${Number(m[2])}. ${m[1]} ${Number(m[4])}:${m[5]}:${m[6]||'00'}`:'\u2014'};
const auditDate=v=>v?new Date(v).toLocaleString('cs-CZ'):'\u2014';
const message=(text,error=false)=>document.querySelector('#message').innerHTML=text?`<div class="message ${error?'error':''}">${esc(text)}</div>`:'';
const query=()=>{const q=new URLSearchParams({page:String(page),per_page:document.querySelector('#perPage').value});for(const [id,key] of [['dateFrom','date_from'],['dateTo','date_to'],['provider','provider'],['driver','driver_id'],['card','card'],['search','search']]){const value=document.querySelector(`#${id}`).value.trim();if(value)q.set(key,value)}return q};
async function load(){try{message('');const data=await api(`/api/v1/fuel-transactions?${query()}`);filterDrivers=data.filters?.drivers||filterDrivers;const selected=document.querySelector('#driver').value;document.querySelector('#driver').innerHTML='<option value="">V\u0161ichni \u0159idi\u010di</option>'+filterDrivers.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');document.querySelector('#driver').value=selected;const items=data.items||[],p=data.pagination||{};lastPage=p.last_page||1;document.querySelector('#total').textContent=`Celkem ${p.total||0} z\u00e1znam\u016f`;document.querySelector('#pageInfo').textContent=`Strana ${p.page||1} z ${lastPage}`;document.querySelector('#previous').disabled=page<=1;document.querySelector('#next').disabled=page>=lastPage;document.querySelector('#rows').innerHTML=items.map(x=>`<tr><td>${esc(sourceDate(x.occurred_at))}</td><td>${esc(x.station_name||'\u2014')}</td><td>${esc(x.product_name||'\u2014')}</td><td>${esc(number(x.quantity))} ${esc(x.unit_of_measure||'')}</td><td><b>${esc(money(x.gross_amount,x.currency))}</b></td><td>${esc(x.masked_card||'\u2014')}</td><td>${esc(x.imported_driver?.name||'\u2014')}</td><td class="${x.driver_attribution_revision?'driver-change':''}">${esc(x.effective_driver?.name||'\u2014')}</td><td>${esc(x.vehicle_registration||'\u2014')}</td><td><button class="secondary" data-change="${x.public_id}">Zm\u011bnit \u0159idi\u010de</button></td></tr>`).join('')||'<tr><td colspan="10">Nebyla nalezena \u017e\u00e1dn\u00e1 tankov\u00e1n\u00ed.</td></tr>';document.querySelectorAll('[data-change]').forEach(button=>button.onclick=()=>openDriver(button.dataset.change))}catch(error){message(error.message,true)}}
async function openDriver(id){try{activeId=id;const [detail,eligible]=await Promise.all([api(`/api/v1/fuel-transactions/${id}/driver-attribution`),api(`/api/v1/fuel-transactions/${id}/eligible-drivers`)]);attribution=detail;document.querySelector('#actualDriver').innerHTML=(eligible.items||[]).map(x=>`<option value="${x.driver_id}" ${Number(x.driver_id)===Number(detail.effective_driver_id)?'selected':''}>${esc(x.driver_name)}</option>`).join('');document.querySelector('#reason').value='';document.querySelector('#summary').innerHTML=`<p><b>Dr\u017eitel karty:</b> ${esc(detail.imported_driver?.name||'\u2014')} &middot; <b>Skute\u010dn\u00fd \u0159idi\u010d:</b> ${esc((detail.actual_driver||detail.imported_driver)?.name||'\u2014')}</p>`;document.querySelector('#history').innerHTML='<b>Historie zm\u011bn</b>'+((detail.history||[]).map(x=>`<div class="history-item"><b>${esc(x.previous_driver_name||'\u2014')} \u2192 ${esc(x.new_driver_name)}</b><br>${esc(x.reason)} &middot; ${esc(auditDate(x.corrected_at))}</div>`).join('')||'<p>Zat\u00edm bez zm\u011bny.</p>');document.querySelector('#history').classList.add('hidden');document.querySelector('#historyToggle').textContent='Zobrazit historii';document.querySelector('#modal').classList.remove('hidden');updateSave()}catch(error){message(error.message,true)}}
const updateSave=()=>document.querySelector('#saveDriver').disabled=Number(document.querySelector('#actualDriver').value)===Number(attribution?.effective_driver_id);
document.querySelector('#actualDriver').onchange=updateSave;document.querySelector('#saveDriver').onclick=async()=>{try{await api(`/api/v1/fuel-transactions/${activeId}/driver-attributions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({driver_id:Number(document.querySelector('#actualDriver').value),expected_revision:attribution.revision,reason:document.querySelector('#reason').value})});document.querySelector('#modal').classList.add('hidden');message('Zm\u011bna \u0159idi\u010de byla ulo\u017eena.');await load()}catch(error){message(error.message,true)}};
document.querySelector('#historyToggle').onclick=()=>{const element=document.querySelector('#history'),hidden=element.classList.toggle('hidden');document.querySelector('#historyToggle').textContent=hidden?'Zobrazit historii':'Skr\u00fdt historii'};document.querySelector('#close').onclick=()=>document.querySelector('#modal').classList.add('hidden');document.querySelector('#filters').onsubmit=event=>{event.preventDefault();page=1;load()};document.querySelector('#reset').onclick=()=>{document.querySelector('#filters').reset();page=1;load()};document.querySelector('#reload').onclick=load;document.querySelector('#perPage').onchange=()=>{page=1;load()};document.querySelector('#previous').onclick=()=>{if(page>1){page--;load()}};document.querySelector('#next').onclick=()=>{if(page<lastPage){page++;load()}};load();
</script>
</body>
</html>