<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Importy paliva | TMS</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#172033;font:14px Arial,sans-serif}.page{max-width:1400px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;align-items:center}.back{color:#334155;font-weight:700;text-decoration:none}h1{margin:18px 0 4px}.lead{color:#64748b}.panel{background:#fff;border:1px solid #dbe3ee;border-radius:14px;padding:18px;margin-top:18px}.toolbar,.filters{display:flex;gap:10px;flex-wrap:wrap;align-items:end}.field{display:grid;gap:6px}label{font-weight:700}input,select,textarea,button{font:inherit;border:1px solid #cbd5e1;border-radius:8px;padding:10px}button{background:#173b72;color:#fff;border:0;font-weight:700;cursor:pointer}button.secondary{background:#e8eef7;color:#173b72}.stats{display:grid;grid-template-columns:repeat(5,minmax(120px,1fr));gap:10px;margin-top:16px}.stat{padding:14px;border-radius:10px;background:#f8fafc}.stat strong{display:block;font-size:22px}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}th{background:#f8fafc}.badge{padding:4px 8px;border-radius:99px;background:#e2e8f0;font-weight:700}.review{background:#fef3c7}.rejected{background:#fee2e2}.accepted{background:#dcfce7}.duplicate{background:#e0e7ff}.hidden{display:none}.modal.hidden{display:none}.history{margin-top:14px;padding:12px;background:#f8fafc;border-radius:8px}.history-item{padding:8px 0;border-bottom:1px solid #e2e8f0}.msg{margin-top:12px;padding:10px;border-radius:8px;background:#eef2ff}.error{background:#fee2e2;color:#991b1b}.json{max-width:380px;white-space:pre-wrap;word-break:break-word;font:12px monospace}.modal{position:fixed;inset:0;background:#0008;display:grid;place-items:center;padding:20px}.dialog{background:#fff;border-radius:14px;padding:20px;width:min(760px,100%)}textarea{width:100%;min-height:130px}.finalization{margin-top:14px;padding:14px;border:1px solid #bfdbfe;background:#eff6ff;border-radius:10px}.finalization.done{border-color:#86efac;background:#f0fdf4}button:disabled{opacity:.55;cursor:not-allowed}
</style></head><body><main class="page"><div class="top"><a class="back" href="/settings">← Nastavení</a><button class="secondary" id="reload">Obnovit</button></div><h1>Importy paliva</h1><p class="lead">ORLEN CSV a MOL XLSX · kontrola dávek, problematických řádků a auditovaných oprav.</p>
<section class="panel"><form id="upload" class="toolbar"><div class="field"><label>Poskytovatel</label><select id="provider"><option>ORLEN</option><option>MOL</option></select></div><div class="field"><label>Soubor</label><input id="file" type="file" required></div><button>Nahrát a zpracovat</button></form><div id="message"></div></section>
<section class="panel"><h2>Importní dávky</h2><table><thead><tr><th>Soubor</th><th>Poskytovatel</th><th>Období</th><th>Stav</th><th>Řádky</th><th></th></tr></thead><tbody id="batches"></tbody></table></section>
<section class="panel hidden" id="detail"><h2 id="detailTitle">Detail dávky</h2><div class="stats" id="stats"></div><div class="filters"><div class="field"><label>Stav řádku</label><select id="status"><option value="">Všechny</option><option>accepted</option><option>duplicate</option><option>review</option><option>rejected</option></select></div></div><table><thead><tr><th>Řádek</th><th>Stav</th><th>Původní data</th><th>Normalizovaná data</th><th>Problém</th><th></th></tr></thead><tbody id="rows"></tbody></table></section></main>
<div id="modal" class="modal hidden"><div class="dialog"><h2>Kontrola &#345;&#225;dku <span id="rowNo"></span></h2><div class="field"><label>Opraven&#225; data (JSON)</label><textarea id="payload"></textarea></div><div class="field"><label>D&#367;vod opravy (min. 10 znak&#367;)</label><textarea id="reason"></textarea></div><div id="history" class="history"></div><div id="finalization" class="finalization"><strong>Fin&#225;ln&#237; potvrzen&#237; opravy</strong><p>Finalizovat lze pouze nejnov&#283;j&#353;&#237; auditovanou revizi. Po potvrzen&#237; se znovu ov&#283;&#345;&#237; karta, p&#345;i&#345;azen&#237; a duplicita transakce.</p><div class="field"><label>D&#367;vod finalizace (min. 10 znak&#367;)</label><textarea id="finalReason"></textarea></div><div id="finalizationAudit"></div></div><div class="toolbar"><button id="save">Ulo&#382;it revizi</button><button id="finalize">Finalizovat nejnov&#283;j&#353;&#237; revizi</button><button class="secondary" id="cancel">Zru&#353;it</button></div></div></div>
<script>
const token=sessionStorage.getItem('tms_mvp_token')||'',org='1';let current=null,activeRow=null,activeDetail=null,allRows=[];
const api=async(path,opt={})=>{const h=new Headers(opt.headers||{});h.set('Accept','application/json');h.set('X-Organization-ID',org);if(token)h.set('Authorization',`Bearer ${token}`);const r=await fetch(path,{...opt,headers:h});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(Object.values(b.errors||{}).flat().join(' ')||b.message||`HTTP ${r.status}`);return b.data};
const fmtDate=v=>v?new Intl.DateTimeFormat('cs-CZ').format(new Date(v)):'—';
const labels={completed:'Dokončeno',completed_with_review:'Vyžaduje kontrolu',accepted:'Přijato',duplicate:'Duplicita',review:'Ke kontrole',rejected:'Odmítnuto'};const label=v=>labels[v]||v;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const msg=(t,e=false)=>document.querySelector('#message').innerHTML=`<div class="msg ${e?'error':''}">${esc(t)}</div>`;
async function load(){try{const response=await api('/api/v1/fuel-imports'),items=response.items||[];document.querySelector('#batches').innerHTML=items.map(b=>`<tr><td>${esc(b.original_filename)}</td><td>${esc(b.provider)}</td><td>${fmtDate(b.period_start)} – ${fmtDate(b.period_end)}</td><td><span class="badge">${esc(label(b.status))}</span></td><td>${b.source_row_count}</td><td><button data-batch="${b.public_id}">Otevřít</button></td></tr>`).join('')||'<tr><td colspan="6">Zatím žádné dávky.</td></tr>';document.querySelectorAll('[data-batch]').forEach(x=>x.onclick=()=>openBatch(x.dataset.batch));}catch(e){msg(e.message,true)}}
async function openBatch(id){try{current=await api(`/api/v1/fuel-imports/${id}`);allRows=current.rows||[];document.querySelector('#detail').classList.remove('hidden');document.querySelector('#detailTitle').textContent=`Detail: ${current.original_filename}`;document.querySelector('#stats').innerHTML=[['Zdroj',current.source_row_count],['Přijato',current.accepted_row_count],['Duplicity',current.duplicate_row_count],['Ke kontrole',current.review_row_count],['Odmítnuto',current.rejected_row_count]].map(x=>`<div class="stat">${x[0]}<strong>${x[1]||0}</strong></div>`).join('');renderRows();}catch(e){msg(e.message,true)}}
function renderRows(){const s=document.querySelector('#status').value,rows=allRows.filter(r=>!s||r.status===s);document.querySelector('#rows').innerHTML=rows.map(r=>`<tr><td>${r.source_row}</td><td><span class="badge ${r.status}" >${label(r.status)}</span></td><td class="json">${esc(JSON.stringify(r.raw_payload,null,2))}</td><td class="json">${esc(JSON.stringify(r.normalized_payload,null,2))}</td><td>${esc((r.validation_messages||[]).join?.(' ')||JSON.stringify(r.validation_messages||''))}</td><td>${['review','rejected'].includes(r.status)?`<button data-row="${r.source_row}">Opravit / finalizovat</button>`:r.status==='accepted'?`<button class="secondary" data-row="${r.source_row}">Detail auditu</button>`:''}</td></tr>`).join('');document.querySelectorAll('[data-row]').forEach(x=>x.onclick=()=>edit(Number(x.dataset.row)));}
async function edit(n){try{activeRow=n;activeDetail=await api(`/api/v1/fuel-imports/${current.public_id}/rows/${n}`);const r=activeDetail,corrections=r.corrections||[],latest=corrections.at(-1),done=r.finalization;document.querySelector('#rowNo').textContent=n;document.querySelector('#payload').value=JSON.stringify(r.effective_payload||r.normalized_payload||r.raw_payload,null,2);document.querySelector('#reason').value='';document.querySelector('#finalReason').value='';document.querySelector('#history').innerHTML='<strong>Historie reviz\u00ed</strong>'+(corrections.map(x=>`<div class="history-item"><b>Revize ${x.revision}</b> \u00b7 ${esc(x.corrected_by?.name||'Nezn\u00e1m\u00fd u\u017eivatel')} \u00b7 ${fmtDate(x.created_at)}<br>${esc(x.reason)}<pre class="json">${esc(JSON.stringify(x.corrected_payload,null,2))}</pre></div>`).join('')||'<p>Zat\u00edm bez p\u0159edchoz\u00ed opravy.</p>');document.querySelector('#finalization').classList.toggle('done',!!done);document.querySelector('#finalizationAudit').innerHTML=done?`<p><b>Finalizov\u00e1no:</b> revize ${done.correction_revision} \u00b7 ${esc(done.finalized_by?.name||'Nezn\u00e1m\u00fd u\u017eivatel')} \u00b7 ${fmtDate(done.finalized_at)}<br><b>D\u016fvod:</b> ${esc(done.reason)}<br><b>Transakce:</b> ${esc(done.transaction_public_id)}</p>`:`<p>${latest?`P\u0159ipravena revize ${latest.revision}.`:'Nejprve ulo\u017ete alespo\u0148 jednu opravu.'}</p>`;document.querySelector('#payload').disabled=!!done;document.querySelector('#reason').disabled=!!done;document.querySelector('#save').disabled=!!done||!['review','rejected'].includes(r.status);document.querySelector('#finalize').disabled=!!done||!latest||!['review','rejected'].includes(r.status);document.querySelector('#finalReason').disabled=!!done;document.querySelector('#modal').classList.remove('hidden')}catch(e){msg(e.message,true)}}
document.querySelector('#save').onclick=async()=>{try{await api(`/api/v1/fuel-imports/${current.public_id}/rows/${activeRow}/corrections`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({corrected_payload:JSON.parse(document.querySelector('#payload').value),reason:document.querySelector('#reason').value})});msg('Oprava byla ulo\u017eena do auditn\u00ed historie.');await openBatch(current.public_id);await edit(activeRow)}catch(e){msg(e.message,true)}};document.querySelector('#finalize').onclick=async()=>{try{const latest=(activeDetail?.corrections||[]).at(-1);if(!latest)throw new Error('Nejprve ulo\u017ete auditovanou opravu.');await api(`/api/v1/fuel-imports/${current.public_id}/rows/${activeRow}/finalization`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_correction_revision:latest.revision,reason:document.querySelector('#finalReason').value})});document.querySelector('#modal').classList.add('hidden');msg('\u0158\u00e1dek byl finalizov\u00e1n a transakce bezpe\u010dn\u011b p\u0159ijata.');await openBatch(current.public_id)}catch(e){msg(e.message,true)}};
document.querySelector('#cancel').onclick=()=>document.querySelector('#modal').classList.add('hidden');document.querySelector('#status').onchange=renderRows;document.querySelector('#reload').onclick=load;
document.querySelector('#upload').onsubmit=async e=>{e.preventDefault();try{const f=new FormData();f.append('provider',document.querySelector('#provider').value);f.append('file',document.querySelector('#file').files[0]);await api('/api/v1/fuel-imports',{method:'POST',body:f});msg('Import byl zpracován.');await load()}catch(x){msg(x.message,true)}};load();
</script></body></html>
