<!doctype html>
<html lang="cs">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Dodavatelské faktury PHM</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#172033;font:14px Arial,sans-serif}.page{max-width:1500px;margin:auto;padding:28px}.top,.head,.actions,.pager,.summary{display:flex;gap:10px;align-items:center;justify-content:space-between;flex-wrap:wrap}.back{color:#334155;font-weight:700;text-decoration:none}h1{margin:18px 0 4px}.muted{color:#64748b}.panel{background:#fff;border:1px solid #dbe3ee;border-radius:14px;padding:18px;margin-top:18px}.filters{display:grid;grid-template-columns:2fr 1fr auto auto;gap:10px;align-items:end}.field{display:grid;gap:6px}label{font-weight:700}input,select,button{font:inherit;border:1px solid #cbd5e1;border-radius:8px;padding:10px;min-width:0}button,.button{background:#173b72;color:#fff;border:0;font-weight:700;cursor:pointer;text-decoration:none;display:inline-block}.secondary{background:#e8eef7;color:#173b72}.danger{background:#fee2e2;color:#991b1b}.message{margin-top:12px;padding:10px;border-radius:8px;background:#eef2ff}.error{background:#fee2e2;color:#991b1b}.hidden{display:none!important}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;margin-top:14px;min-width:1050px}th,td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}th{background:#f8fafc}.badge{display:inline-block;padding:5px 8px;border-radius:999px;font-weight:700}.unallocated{background:#fee2e2;color:#991b1b}.partially_allocated{background:#fef3c7;color:#92400e}.fully_allocated,.active{background:#dcfce7;color:#166534}.reversed{background:#e2e8f0;color:#475569}.modal{position:fixed;inset:0;background:#0008;display:grid;place-items:center;padding:18px;z-index:5}.dialog{background:#fff;border-radius:14px;padding:20px;width:min(1100px,100%);max-height:94vh;overflow:auto}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.card{background:#f8fafc;border-radius:10px;padding:12px}.card strong{display:block;font-size:20px;margin-top:5px}.allocation-form{display:grid;grid-template-columns:2fr 1fr 2fr auto;gap:10px;align-items:end;margin-top:14px}@media(max-width:800px){.filters,.allocation-form,.cards{grid-template-columns:1fr}}
</style>
</head>
<body><main class="page">
<div class="top"><a class="back" href="/settings/fuel-transactions">&larr; Tankování PHM</a><button id="reload" class="secondary">Obnovit</button></div>
<h1>Dodavatelské faktury PHM</h1><p class="muted">Evidence přijatých faktur a jejich přesné přiřazení k tankováním. Bankovní párování a označení úhrady nejsou součástí této obrazovky.</p>
<section class="panel"><form id="filters" class="filters"><div class="field"><label for="search">Hledat</label><input id="search" placeholder="Číslo faktury, variabilní symbol nebo dodavatel"></div><div class="field"><label for="status">Stav dokladu</label><select id="status"><option value="">Všechny</option><option value="draft">Koncept</option></select></div><button type="submit">Filtrovat</button><button id="reset" type="button" class="secondary">Zrušit filtr</button></form><div id="message"></div><div class="table-wrap"><table><thead><tr><th>Číslo</th><th>Dodavatel</th><th>Datum</th><th>Splatnost</th><th>Celkem</th><th>Alokováno</th><th>Zbývá</th><th>Stav alokace</th><th>Akce</th></tr></thead><tbody id="rows"></tbody></table></div><div class="pager"><span id="total"></span><div class="actions"><button id="previous" class="secondary">Předchozí</button><span id="pageInfo"></span><button id="next" class="secondary">Další</button></div></div></section>
</main>
<div id="detailModal" class="modal hidden"><section class="dialog"><div class="head"><h2 id="detailTitle">Detail faktury</h2><button id="closeDetail" class="secondary">Zavřít</button></div><div id="detailIdentity"></div><div id="detailCards" class="cards"></div><h3>Nové přiřazení tankování</h3><div class="allocation-form"><div class="field"><label for="fuelTransaction">Tankování</label><select id="fuelTransaction"></select></div><div class="field"><label for="allocationAmount">Částka</label><input id="allocationAmount" inputmode="decimal" placeholder="0.00"></div><div class="field"><label for="allocationReason">Důvod</label><input id="allocationReason" minlength="3" maxlength="1000" placeholder="Důvod přiřazení"></div><button id="createAllocation">Přiřadit</button></div><p class="muted">Částka se validuje přesně na haléře; součet aktivních alokací nesmí překročit fakturu ani tankování.</p><h3>Historie alokací</h3><div class="table-wrap"><table><thead><tr><th>Tankování</th><th>Částka</th><th>Stav</th><th>Důvod</th><th>Audit</th><th>Akce</th></tr></thead><tbody id="allocationRows"></tbody></table></div><div id="detailMessage"></div></section></div>
<script>
const token=sessionStorage.getItem('tms_mvp_token')||'',org=sessionStorage.getItem('tms_mvp_organization_id')||'';let page=1,lastPage=1,activeInvoice=null,transactions=[];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const moneyMinor=(minor,currency='CZK')=>`${(Number(minor||0)/100).toLocaleString('cs-CZ',{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency}`;
const date=value=>value?new Date(`${value}T00:00:00`).toLocaleDateString('cs-CZ'):'—';
const stateLabels={unallocated:'Nepřiřazeno',partially_allocated:'Částečně přiřazeno',fully_allocated:'Plně přiřazeno',active:'Aktivní',reversed:'Stornováno'};
async function api(path,opt={}){const headers=new Headers(opt.headers||{});headers.set('Accept','application/json');headers.set('X-Organization-ID',org);if(token)headers.set('Authorization',`Bearer ${token}`);const response=await fetch(path,{...opt,headers});const body=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(Object.values(body.errors||{}).flat().join(' ')||body.message||`HTTP ${response.status}`);error.status=response.status;throw error}return body.data}
function showMessage(text,isError=false,detail=false){const box=document.querySelector(detail?'#detailMessage':'#message');box.innerHTML=text?`<div class="message ${isError?'error':''}">${esc(text)}</div>`:''}
function query(){const q=new URLSearchParams({page:String(page),per_page:'25'}),search=document.querySelector('#search').value.trim(),status=document.querySelector('#status').value;if(search)q.set('search',search);if(status)q.set('status',status);return q}
async function load(){try{showMessage('');const data=await api(`/api/v1/supplier-fuel-invoices?${query()}`),items=data.items||[],pagination=data.pagination||{};lastPage=pagination.last_page||1;document.querySelector('#rows').innerHTML=items.map(item=>{const summary=item.allocation_summary||{},document=item.billing_document||{},snapshot=item.counterparty_snapshot||{};return `<tr><td><b>${esc(item.document_number)}</b><br><span class="muted">VS ${esc(item.variable_symbol||'—')}</span></td><td>${esc(snapshot.name||'—')}</td><td>${esc(date(item.issued_on))}</td><td>${esc(date(item.due_on))}</td><td><b>${esc(moneyMinor(summary.invoice_amount_minor,summary.currency))}</b></td><td>${esc(moneyMinor(summary.active_allocated_amount_minor,summary.currency))}</td><td>${esc(moneyMinor(summary.unallocated_amount_minor,summary.currency))}</td><td><span class="badge ${esc(summary.state)}">${esc(stateLabels[summary.state]||summary.state)}</span><br><span class="muted">${esc(document.status||'—')}</span></td><td><button data-detail="${esc(item.public_id)}" class="secondary">Otevřít detail</button></td></tr>`}).join('')||'<tr><td colspan="9">Žádné dodavatelské faktury PHM.</td></tr>';document.querySelector('#total').textContent=`Celkem ${pagination.total||0} faktur`;document.querySelector('#pageInfo').textContent=`Strana ${pagination.current_page||1} z ${lastPage}`;document.querySelector('#previous').disabled=page<=1;document.querySelector('#next').disabled=page>=lastPage;document.querySelectorAll('[data-detail]').forEach(button=>button.onclick=()=>openDetail(button.dataset.detail))}catch(error){showMessage(error.message,true)}}
async function loadTransactions(){const data=await api('/api/v1/fuel-transactions?per_page=100');transactions=data.items||[];document.querySelector('#fuelTransaction').innerHTML='<option value="">Vyberte tankování</option>'+transactions.map(item=>`<option value="${esc(item.public_id)}">${esc(date(String(item.occurred_at||'').slice(0,10)))} · ${esc(item.provider||'—')} · ${esc(item.station_name||'—')} · ${esc(item.gross_amount||'0')} ${esc(item.currency||'')}</option>`).join('')}
function renderDetail(item){activeInvoice=item;const summary=item.allocation_summary||{},snapshot=item.counterparty_snapshot||{};document.querySelector('#detailTitle').textContent=`Faktura ${item.document_number||''}`;document.querySelector('#detailIdentity').innerHTML=`<p><b>${esc(snapshot.name||'—')}</b> · IČO ${esc(snapshot.registration_number||'—')} · VS ${esc(item.variable_symbol||'—')}</p>`;document.querySelector('#detailCards').innerHTML=`<div class="card"><span>Částka faktury</span><strong>${esc(moneyMinor(summary.invoice_amount_minor,summary.currency))}</strong></div><div class="card"><span>Aktivně přiřazeno</span><strong>${esc(moneyMinor(summary.active_allocated_amount_minor,summary.currency))}</strong></div><div class="card"><span>Zbývá přiřadit</span><strong>${esc(moneyMinor(summary.unallocated_amount_minor,summary.currency))}</strong></div>`;document.querySelector('#allocationRows').innerHTML=(item.allocations||[]).map(allocation=>{const fuel=allocation.fuel_transaction||{},events=allocation.events||[],canReverse=allocation.status==='active';return `<tr><td><b>${esc(fuel.provider||'—')} ${esc(fuel.provider_transaction_identifier||'')}</b><br>${esc(fuel.station_name||'—')} · ${esc(fuel.occurred_at||'—')}</td><td>${esc(moneyMinor(allocation.allocated_amount_minor,allocation.currency))}</td><td><span class="badge ${esc(allocation.status)}">${esc(stateLabels[allocation.status]||allocation.status)}</span></td><td>${esc(allocation.reason||'—')}</td><td>${events.length} událostí · revize ${esc(allocation.revision)}</td><td>${canReverse?`<button class="danger" data-reverse="${esc(allocation.public_id)}" data-revision="${esc(allocation.revision)}">Stornovat</button>`:'—'}</td></tr>`}).join('')||'<tr><td colspan="6">Zatím bez alokací.</td></tr>';document.querySelectorAll('[data-reverse]').forEach(button=>button.onclick=()=>reverseAllocation(button.dataset.reverse,Number(button.dataset.revision)))}
async function openDetail(id){try{showMessage('',false,true);const [detail]=await Promise.all([api(`/api/v1/supplier-fuel-invoices/${id}`),transactions.length?Promise.resolve():loadTransactions()]);renderDetail(detail);document.querySelector('#allocationAmount').value='';document.querySelector('#allocationReason').value='';document.querySelector('#detailModal').classList.remove('hidden')}catch(error){showMessage(error.message,true)}}
async function refreshDetail(){renderDetail(await api(`/api/v1/supplier-fuel-invoices/${activeInvoice.public_id}`))}
document.querySelector('#createAllocation').onclick=async()=>{const transaction=document.querySelector('#fuelTransaction').value,amount=document.querySelector('#allocationAmount').value.trim(),reason=document.querySelector('#allocationReason').value.trim();if(!transaction||!amount||reason.length<3){showMessage('Vyberte tankování, zadejte částku a důvod alespoň 3 znaky.',true,true);return}try{await api(`/api/v1/supplier-fuel-invoices/${activeInvoice.public_id}/fuel-transaction-allocations`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idempotency_key:crypto.randomUUID(),fuel_transaction_public_id:transaction,allocated_amount:amount,reason})});showMessage('Tankování bylo přiřazeno.',false,true);await refreshDetail();await load()}catch(error){showMessage(error.message,true,true)}};
async function reverseAllocation(id,revision){const reason=prompt('Uveďte důvod storna alokace (alespoň 3 znaky):','Chybné přiřazení tankování.');if(reason===null)return;if(reason.trim().length<3){showMessage('Důvod storna musí mít alespoň 3 znaky.',true,true);return}try{await api(`/api/v1/supplier-fuel-invoices/${activeInvoice.public_id}/fuel-transaction-allocations/${id}/reverse`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_revision:revision,reason:reason.trim()})});showMessage('Alokace byla auditně stornována.',false,true);await refreshDetail();await load()}catch(error){if(error.status===422)await refreshDetail().catch(()=>{});showMessage(error.message,true,true)}}
document.querySelector('#closeDetail').onclick=()=>document.querySelector('#detailModal').classList.add('hidden');document.querySelector('#filters').onsubmit=event=>{event.preventDefault();page=1;load()};document.querySelector('#reset').onclick=()=>{document.querySelector('#filters').reset();page=1;load()};document.querySelector('#reload').onclick=load;document.querySelector('#previous').onclick=()=>{if(page>1){page--;load()}};document.querySelector('#next').onclick=()=>{if(page<lastPage){page++;load()}};load();
</script></body></html>